// The single source of truth for the course map.
// generate.mjs turns it into Part / Phase / Module / Project READMEs + PROGRESS.md.

const REVIEW = 'Module Review';
const DS = (name) => [`What a ${name} Is & When to Use It`, `Implementing a ${name}`, 'Complexity & Trade-offs', 'Practice Problems', REVIEW];
const ALGO = (name) => [`${name}: The Idea`, `Implementing ${name}`, 'Complexity & Edge Cases', 'Practice Problems', REVIEW];
const PATTERN = (name) => ['The Problem It Solves', `The ${name} Pattern`, 'Implementation in JavaScript', 'When NOT to Use It', REVIEW];

export const parts = [
  { n: 1, folder: 'Part1.JavaScript', title: 'JavaScript Mastery', goal: 'Understand JavaScript deeply enough to build anything without a framework: the language, how it executes, async, the browser, Node.js, algorithms, patterns and testing.' },
  { n: 2, folder: 'Part2.TypeScript', title: 'TypeScript Mastery', goal: 'Add a static type system on top of that JavaScript: model domains precisely, write generic APIs and declaration files, configure TypeScript professionally, and run large type-safe systems.' },
];

// weights: A = Phases 1–16, B = Phases 17–30 (architecture matters more as you mature)
export const weights = {
  A: { 'Language knowledge': 20, 'Coding exercises': 20, 'Problem solving / algorithms': 15, Debugging: 15, Projects: 20, 'Code design / architecture': 10 },
  B: { 'Language knowledge': 10, 'Coding exercises': 15, 'Problem solving / algorithms': 15, Debugging: 15, Projects: 25, 'Code design / architecture': 20 },
};

export const phases = [
  // ───────────────────────── PART I: JAVASCRIPT ─────────────────────────
  { n: 1, part: 1, slug: 'ProgrammingFoundations', title: 'Programming Foundations', weeks: 1, goal: 'Know what a program is, how JavaScript source becomes running behaviour, and how to debug like an engineer.', modules: [
    { n: 1, slug: 'IntroductionToProgramming', title: 'Introduction to Programming', ready: true,
      bigIdea: 'A program is a recipe that a very fast, very literal cook follows. It works with values, remembers things (state), takes input and produces output, and when it goes wrong you investigate like a detective, not a gambler.',
      lessons: ['What Programming Really Is', 'Values, Expressions & Statements', 'From Source Code to Running Program', 'The Debugging Mindset', REVIEW],
      explain: ['What is the difference between an expression and a statement? Give three of each.', 'What is "state", and why does it make programs harder to reason about?', 'Why does a syntax error stop a JavaScript file before its first line runs?', 'Describe the scientific method of debugging in five steps.'],
      build: ['A traffic-light state machine', 'A "does it fail at parse time or run time?" detector', 'A bisect function that finds the first bad version'] },
    { n: 2, slug: 'TheJavaScriptEnvironment', title: 'The JavaScript Environment', ready: true,
      bigIdea: 'JavaScript is a language (ECMAScript) that lives inside a host: a browser or Node.js. The language gives you arrays and functions; the host gives you things like document, fetch and files. Knowing which is which removes half of all beginner confusion.',
      lessons: ['ECMAScript vs JavaScript', 'Engines, Hosts & Runtimes', 'Running JavaScript: Console, REPL & Files', 'Strict Mode', 'Modules: A First Look', REVIEW],
      explain: ['What is TC39 and how does a feature get into JavaScript?', 'Is console.log part of the JavaScript language? Who provides it?', 'Name four things strict mode changes and why each makes code safer.', 'What changes when a file is treated as a module instead of a script?'],
      build: ['An ECMAScript edition namer', 'A syntax-support detector', 'A global-name classifier (language vs browser vs Node)', 'A sloppy-vs-strict mode comparison tool'] },
  ] },
  { n: 2, part: 1, slug: 'JavaScriptFundamentals', title: 'JavaScript Fundamentals', weeks: 2, goal: 'Master values, variables and operators, including the strange cases and why they happen.', modules: [
    { n: 3, slug: 'VariablesAndValues', title: 'Variables & Values',
      bigIdea: 'A variable is a labelled box, but some boxes hold the thing itself (primitives) and some hold a map to where the thing lives (references). Most "JavaScript is weird" moments come from forgetting which kind of box you have.',
      lessons: ['Declaration, Assignment & Initialization', 'let, const and the Trouble with var', 'The Primitive Types: string, number, boolean, undefined, null', 'BigInt & Symbol', 'Value vs Reference', 'Mutability vs Immutability', REVIEW],
      explain: ['Why can you push into a const array but not reassign it?', 'What exactly is copied when you assign an object to a new variable?', 'undefined vs null: who produces each, and when should you use null?', 'When do you need BigInt?'],
      build: ['A value-vs-reference visualiser', 'A safe money counter using BigInt cents'] },
    { n: 4, slug: 'OperatorsAndExpressions', title: 'Operators & Expressions',
      bigIdea: 'Operators are verbs that combine values into new values. JavaScript\'s verbs sometimes quietly convert types first (coercion). Learn the conversion rules and `[] == false` stops being magic.',
      lessons: ['Arithmetic & Numeric Edge Cases (NaN, Infinity, -0)', 'Comparison, Equality & Strict Equality', 'Type Coercion: The Rules Behind the Weirdness', 'Logical Operators & Short-Circuit Evaluation', 'Nullish Coalescing & Optional Chaining', 'Assignment, Ternary & Operator Precedence', REVIEW],
      explain: ['Walk through, step by step, why `[] == false` is true.', 'When is `||` the wrong choice and `??` the right one?', 'Why is NaN !== NaN, and how do you test for NaN?', 'What does short-circuit evaluation let you avoid?'],
      build: ['looseEquals(a, b): a simplified version of the spec\'s == algorithm'] },
  ] },
  { n: 3, part: 1, slug: 'ProgramFlow', title: 'Program Flow', weeks: 1, goal: 'Control flow that is correct, readable and chosen deliberately.', modules: [
    { n: 5, slug: 'Conditionals', title: 'Conditionals',
      bigIdea: 'Conditionals are forks in the road. Good code has few, clear forks: it deals with the odd cases at the door (guard clauses) so the main path stays straight.',
      lessons: ['if / else and Blocks', 'Truthy & Falsy Values', 'switch and Fall-Through', 'Guard Clauses & Early Returns', 'Conditional Expressions & Lookup Tables', REVIEW],
      explain: ['List all falsy values in JavaScript.', 'When is a lookup object better than a switch?', 'Why do guard clauses make functions easier to read?'],
      build: ['Refactor a nested-if "pyramid of doom" into guard clauses'] },
    { n: 6, slug: 'LoopsAndIteration', title: 'Loops & Iteration',
      bigIdea: 'Loops repeat work. The skill is not writing loops, it is choosing the right one, and knowing when an array method or no loop at all says it better.',
      lessons: ['for, while & do...while', 'for...of vs for...in', 'break, continue & Labels', 'Choosing the Right Loop (and When Not to Loop)', REVIEW],
      explain: ['Why should you not use for...in on arrays?', 'When is do...while the right tool?', 'What makes an off-by-one error, and how do you prevent it?'],
      build: ['range(start, end, step)', 'A loop-bug hunt'] },
  ] },
  { n: 4, part: 1, slug: 'Functions', title: 'Functions', weeks: 3, goal: 'Functions as the main unit of design, and closures as their superpower.', modules: [
    { n: 7, slug: 'FunctionsFundamentals', title: 'Functions Fundamentals',
      bigIdea: 'A function is a small machine: values go in, a value comes out. In JavaScript the machine itself is also a value, so you can hand machines to other machines (callbacks, higher-order functions).',
      lessons: ['Declarations, Expressions & Arrow Functions', 'Parameters, Arguments, Defaults & Rest', 'Return Values & Early Returns', 'Callbacks & Higher-Order Functions', 'Pure Functions & Side Effects', REVIEW],
      explain: ['What can a function declaration do that an arrow function cannot?', 'What makes a function pure? Why do pure functions test so easily?', 'What is a higher-order function? Name three built into JavaScript.'],
      build: ['once(fn)', 'times(n, fn)', 'applyN(fn, n)'] },
    { n: 8, slug: 'ScopeAndClosures', title: 'Scope & Closures',
      bigIdea: 'Every function carries a backpack holding the variables that were around when it was created. That backpack is a closure. It is how JavaScript does private state, factories and memoization.',
      lessons: ['Global, Function & Block Scope', 'Lexical Scope & the Scope Chain', 'Closures: Functions That Remember', 'Closure Memory: What Is Retained', 'Closure Patterns: Counters, Private State, Factories', 'Memoization', REVIEW],
      explain: ['Why do closures exist? (What would be impossible without them?)', 'Which variables does a closure retain, and what are the memory consequences?', 'How do closures relate to lexical scope?', 'When would a class or a module be clearer than a closure?'],
      build: ['A counter', 'Private state without classes', 'memoize(fn)', 'A configuration factory'] },
  ] },
  { n: 5, part: 1, slug: 'DataStructures', title: 'JavaScript Data Structures', weeks: 3, goal: 'Arrays, objects and collections at expert level, including re-implementing their core methods.', modules: [
    { n: 9, slug: 'Arrays', title: 'Arrays',
      bigIdea: 'An array is a numbered row of lockers. Its methods are ready-made loops. Rebuild them yourself once and you will never forget what map, filter and reduce really do.',
      lessons: ['Creating & Mutating Arrays', 'Traversal & Searching', 'Sorting (and the Default-Sort Trap)', 'Transformations: map, filter, reduce', 'Queries: find, findIndex, some, every', 'Reshaping: flat, flatMap, slice, splice, concat', 'Non-Mutating Alternatives: toSorted, toSpliced, with', REVIEW],
      explain: ['Why does [10, 9, 1].sort() give [1, 10, 9]?', 'Which array methods mutate, and why does that matter in UI code?', 'Explain reduce by implementing it.'],
      build: ['myMap', 'myFilter', 'myReduce', 'myFind', 'myFlat'] },
    { n: 10, slug: 'Objects', title: 'Objects',
      bigIdea: 'An object is a labelled filing cabinet. Beyond get and set, each drawer has hidden settings (descriptors), and copying a cabinet copies the drawers but not necessarily what is inside them.',
      lessons: ['Literals, Properties & Methods', 'Computed Keys, Shorthand & Destructuring', 'Spread & Copying: Shallow vs Deep (structuredClone)', 'Object.keys / values / entries / assign / freeze / seal', 'Property Descriptors', 'Getters & Setters', REVIEW],
      explain: ['What is the difference between a shallow and a deep copy? Show a bug caused by a shallow copy.', 'freeze vs seal vs preventExtensions?', 'What can a property descriptor control?'],
      build: ['deepClone (simplified)', 'pick / omit', 'deepFreeze'] },
    { n: 11, slug: 'Collections', title: 'Collections: Map, Set, WeakMap, WeakSet',
      bigIdea: 'Objects and arrays are general tools. Map, Set and their weak cousins are specialist tools that are faster, safer and clearer for lookups, uniqueness and attaching data to objects without leaking memory.',
      lessons: ['Map vs Object', 'Set and Set Operations', 'WeakMap & WeakSet', 'Choosing the Right Collection', REVIEW],
      explain: ['When does a Map outperform an object?', 'Why can\'t you iterate a WeakMap?', 'Give a real use case for WeakMap.'],
      build: ['An LRU cache using Map', 'union / intersection / difference helpers'] },
  ] },
  { n: 6, part: 1, slug: 'JavaScriptInternals', title: 'JavaScript Internals', weeks: 3, goal: 'Move from JavaScript developer to JavaScript expert: predict exactly what the engine will do.', modules: [
    { n: 12, slug: 'ExecutionContext', title: 'Execution Context',
      bigIdea: 'Every time code runs, the engine sets up a workspace (an execution context) that records which variables exist and what `this` is. Understanding the workspace explains hoisting, closures and `this` at once.',
      lessons: ['What Is an Execution Context?', 'The Global Execution Context', 'Function Execution Contexts', 'Creation Phase vs Execution Phase', 'Environment Records', REVIEW],
      explain: ['What happens in the creation phase vs the execution phase?', 'What is stored in an environment record?', 'How do execution contexts explain closures?'] },
    { n: 13, slug: 'CallStack', title: 'The Call Stack',
      bigIdea: 'The call stack is a stack of plates: each function call adds a plate, and each return removes one. The engine only ever works on the top plate.',
      lessons: ['Stack Frames', 'Recursion on the Stack', 'Stack Overflow', 'Reading Stack Traces & Call-Stack Debugging', REVIEW],
      explain: ['Draw the stack for a() → b() → c() at its deepest point.', 'What causes "Maximum call stack size exceeded"?', 'How do you read a stack trace top to bottom?'],
      build: ['Convert a recursive function to use an explicit stack'] },
    { n: 14, slug: 'Hoisting', title: 'Hoisting',
      bigIdea: '"JavaScript moves declarations to the top" is a white lie. What really happens is that the engine registers names during the creation phase, before running a single line, and each kind of declaration is registered differently.',
      lessons: ['Why "Moved to the Top" Is Misleading', 'Function Declarations', 'var', 'let, const & the Temporal Dead Zone', 'Classes & Hoisting', REVIEW],
      explain: ['What is the Temporal Dead Zone, and why was it added?', 'Why can you call a function declaration before its line, but not a function expression?', 'Explain hoisting without saying "moved to the top".'] },
    { n: 15, slug: 'This', title: 'this',
      bigIdea: '`this` is not "the object the function lives in"; it is decided by how the function is called. Learn the handful of call-site rules and you can predict `this` every time.',
      lessons: ['Why this Exists', 'Default & Implicit Binding', 'Explicit Binding: call, apply, bind', 'new Binding', 'Arrow Functions & Lexical this', 'this in Classes & Event Handlers', REVIEW],
      explain: ['List the binding rules in order of precedence.', 'Why does passing obj.method as a callback lose `this`?', 'Why don\'t arrow functions have their own `this`?'],
      build: ['myCall', 'myApply', 'myBind'] },
  ] },
  { n: 7, part: 1, slug: 'ObjectOrientedJavaScript', title: 'Object-Oriented JavaScript', weeks: 2, goal: 'Understand prototypes as the real mechanism, and classes as the syntax on top.', modules: [
    { n: 16, slug: 'Prototypes', title: 'Prototypes',
      bigIdea: 'When an object doesn\'t know something, it asks its parent (its prototype), which asks its parent, and so on up the chain. That chain of "ask your parent" is all of JavaScript inheritance.',
      lessons: ['Objects Linking to Objects', 'Prototype Lookup', 'Constructor Functions & .prototype', '__proto__ vs Object.getPrototypeOf', 'Object.create', 'Prototypal Inheritance', REVIEW],
      explain: ['What is the difference between `.prototype` and an object\'s prototype?', 'Trace a property lookup through three levels of prototypes.', 'What does `new` do, step by step?'],
      build: ['myNew()', 'myInstanceOf()', 'A hand-built prototype chain'] },
    { n: 17, slug: 'Classes', title: 'Classes',
      bigIdea: 'Classes are a tidier way to write prototypes, plus some genuinely new powers such as private # fields. The bigger lesson is design: when to inherit, and when to compose.',
      lessons: ['Class Syntax: Sugar over Prototypes', 'Fields, Private # Fields & Static Members', 'Inheritance & super', 'Composition over Inheritance', REVIEW],
      explain: ['What do classes add that constructor functions cannot do?', 'Why must a subclass call super() before using this?', 'Inheritance vs composition: argue both sides for one design.'],
      build: ['The same feature designed with inheritance, then with composition'] },
  ] },
  { n: 8, part: 1, slug: 'FunctionalJavaScript', title: 'Functional JavaScript', weeks: 1, goal: 'Build programs from small, pure, composable functions.', modules: [
    { n: 18, slug: 'FunctionalProgramming', title: 'Functional Programming',
      bigIdea: 'Functional programming is building with LEGO: small pieces that always behave the same way, snapped together into bigger pieces. No piece secretly changes another.',
      lessons: ['Purity & Referential Transparency', 'Immutability in Practice', 'Composition: compose & pipe', 'Currying & Partial Application', 'Function Pipelines on Real Data', REVIEW],
      explain: ['What is referential transparency?', 'compose vs pipe?', 'When does currying help, and when is it just clever?'],
      build: ['compose()', 'pipe()', 'curry()', 'partial()'] },
  ] },
  { n: 9, part: 1, slug: 'ErrorHandling', title: 'Error Handling', weeks: 1, goal: 'Design failure handling on purpose, instead of hoping.', modules: [
    { n: 19, slug: 'Errors', title: 'Errors',
      bigIdea: 'Errors are messages in a bottle thrown up the call stack until someone catches them. Good systems decide in advance who catches what, and what the user sees.',
      lessons: ['Error Objects & Built-in Error Types', 'throw, try, catch, finally', 'Custom Error Classes & cause', 'Error Propagation', 'Where to Handle Errors: Application Layers', REVIEW],
      explain: ['When should you catch an error, and when should you let it propagate?', 'What does `finally` guarantee?', 'Why create custom error classes?'],
      build: ['An error hierarchy (ValidationError, NotFoundError…) + a central handler'] },
  ] },
  { n: 10, part: 1, slug: 'DOMAndBrowserProgramming', title: 'DOM & Browser Programming', weeks: 2, goal: 'Build interactive browser interfaces with raw JavaScript.', modules: [
    { n: 20, slug: 'DOMFundamentals', title: 'DOM Fundamentals',
      bigIdea: 'The DOM is a living family tree of your page. JavaScript can walk it, add children, remove them or restyle them, and the screen updates to match.',
      lessons: ['The DOM Tree & Nodes', 'Selecting Elements', 'Creating, Inserting & Removing Elements', 'Attributes, Classes & Styles', 'Forms & Input', REVIEW],
      explain: ['Node vs Element?', 'Why is innerHTML with user input dangerous?', 'What is the cost of changing the DOM in a loop?'] },
    { n: 21, slug: 'Events', title: 'Events',
      bigIdea: 'An event is a shout that travels down the tree (capturing) and back up (bubbling). Delegation means one listener high up hears the shouts of thousands of children.',
      lessons: ['Event Listeners', 'Propagation: Capturing & Bubbling', 'Event Delegation', 'Default Behaviour', 'Custom Events', REVIEW],
      explain: ['Describe the three event phases.', 'Why does delegation scale better than one listener per item?', 'stopPropagation vs preventDefault?'],
      build: ['A small interactive UI toolkit with no framework'] },
  ] },
  { n: 11, part: 1, slug: 'AsynchronousJavaScript', title: 'Asynchronous JavaScript', weeks: 3, goal: 'Write async code that is correct, and predict exactly when each piece runs.', modules: [
    { n: 22, slug: 'AsyncFoundations', title: 'Async Foundations',
      bigIdea: 'JavaScript has one cook who never stands waiting by the oven: they set a timer (callback) and keep cooking other dishes.',
      lessons: ['Synchronous vs Asynchronous Execution', 'Callbacks', 'Callback Problems: Nesting, Inversion of Control, Errors', REVIEW],
      explain: ['What is inversion of control, and why is it a problem?', 'Why can\'t you return a value from inside a callback?'] },
    { n: 23, slug: 'Promises', title: 'Promises',
      bigIdea: 'A promise is a receipt for a value that isn\'t ready yet. It will be fulfilled or rejected exactly once, and you can attach what to do next.',
      lessons: ['Promise States', 'then, catch & finally', 'Chaining', 'Promise.all, allSettled, race, any', 'Build Your Own Promise (simplified)', REVIEW],
      explain: ['What does .then return?', 'all vs allSettled vs race vs any: pick one for four different scenarios.', 'Why are promise callbacks always asynchronous?'],
      build: ['MyPromise (simplified)', 'promisify()'] },
    { n: 24, slug: 'AsyncAwait', title: 'Async / Await',
      bigIdea: 'async/await lets you write "wait for the receipt" code that reads top to bottom, but it is still promises underneath.',
      lessons: ['async Functions', 'await', 'Sequential vs Parallel', 'Error Propagation', 'Concurrency Control', REVIEW],
      explain: ['What does an async function always return?', 'How do you run three requests in parallel with await?', 'How do you limit concurrency to 3 at a time?'],
      build: ['mapWithConcurrency(items, limit, fn)'] },
    { n: 25, slug: 'EventLoop', title: 'The Event Loop',
      bigIdea: 'The event loop is the cook\'s rule for what to do next: finish the current dish, then all the quick "microtask" jobs, then the next queued task, and repeat forever.',
      lessons: ['Call Stack + Runtime APIs', 'The Task (Macrotask) Queue', 'The Microtask Queue', 'Rendering & the Browser Event Loop', 'The Node.js Event Loop Phases', 'Predict-the-Output Drills', REVIEW],
      explain: ['Why does a resolved promise callback run before setTimeout(fn, 0)?', 'How can microtasks starve rendering?', 'Name the Node.js event loop phases in order.'] },
  ] },
  { n: 12, part: 1, slug: 'NetworkProgramming', title: 'Network Programming', weeks: 2, goal: 'Talk to the network reliably, even when the network misbehaves.', modules: [
    { n: 26, slug: 'FetchAndHTTP', title: 'Fetch & HTTP',
      bigIdea: 'fetch is the postal service: you send a request letter and get a response letter back. A "404 Not Found" letter still counts as delivered, so fetch does not treat it as an error.',
      lessons: ['Requests & Responses', 'Headers, JSON & Status Codes', 'Error Handling (fetch doesn\'t reject on 404)', 'AbortController & Timeout Strategies', REVIEW],
      explain: ['When does fetch reject, and when doesn\'t it?', 'How do you add a timeout to fetch?', 'Why read response.ok?'],
      build: ['fetchJson(url, { timeout })'] },
    { n: 27, slug: 'ResilientAsyncSystems', title: 'Resilient Async Systems',
      bigIdea: 'Networks are flaky, users click too fast, and servers get overwhelmed. Resilience utilities are shock absorbers for all three.',
      lessons: ['Retries & Exponential Backoff', 'Debounce & Throttle', 'Rate Limiting', 'Cancellation', 'Queues & Concurrency Limiting', REVIEW],
      explain: ['Debounce vs throttle, with a UI example of each.', 'Why add jitter to backoff?', 'Which requests are safe to retry?'],
      build: ['retry()', 'debounce()', 'throttle()', 'createRateLimiter()', 'TaskQueue'] },
  ] },
  { n: 13, part: 1, slug: 'Modules', title: 'Modules', weeks: 1, goal: 'Understand module systems deeply, because modern JS/TS tooling depends on it.', modules: [
    { n: 28, slug: 'JavaScriptModules', title: 'JavaScript Modules',
      bigIdea: 'Modules are rooms with doors. Everything inside is private unless you put it through the door (export), and other rooms choose what to bring in (import).',
      lessons: ['Why Modules Exist', 'ESM: import & export, Named vs Default', 'Dynamic import()', 'Module Scope, Live Bindings & Cycles', 'CommonJS: require & module.exports', 'Module Resolution & package.json (type, exports)', REVIEW],
      explain: ['ESM vs CommonJS: loading, syntax and live bindings.', 'What does the "exports" field in package.json control?', 'What happens with a circular import?'] },
  ] },
  { n: 14, part: 1, slug: 'AdvancedLanguageFeatures', title: 'Advanced Language Features', weeks: 3, goal: 'The power tools: iteration protocols, generators, symbols, proxies, regex and binary data.', modules: [
    { n: 29, slug: 'Iterators', title: 'Iterators',
      bigIdea: 'An iterator is a Pez dispenser: each time you ask with next(), it hands out one value until it is empty. Anything with a dispenser works with for...of and spread.',
      lessons: ['The Iteration Protocol', 'Symbol.iterator', 'Building Your Own Iterable', REVIEW],
      explain: ['What makes an object iterable?', 'Iterable vs iterator?'], build: ['An iterable Range class', 'An iterable linked list'] },
    { n: 30, slug: 'Generators', title: 'Generators',
      bigIdea: 'A generator is a function you can pause. Every yield hands out a value and freezes the function until you ask for the next one.',
      lessons: ['function* and yield', 'Lazy Sequences', 'Generators as State Machines', 'Async Generators & for await', REVIEW],
      explain: ['How does a generator make lazy processing possible?', 'What does yield return inside the generator?'], build: ['Lazy take / map / filter over infinite sequences'] },
    { n: 31, slug: 'Symbols', title: 'Symbols',
      bigIdea: 'A Symbol is a key nobody else can guess or clash with. Well-known symbols are secret hooks for changing how the language treats your objects.',
      lessons: ['Symbols as Unique Keys', 'Well-Known Symbols', 'Metaprogramming with Symbols', REVIEW],
      explain: ['Why use a Symbol key instead of a string?', 'Name three well-known symbols and what they customise.'] },
    { n: 32, slug: 'ProxyAndReflect', title: 'Proxy & Reflect',
      bigIdea: 'A Proxy is a receptionist standing in front of an object: every get, set or delete goes through them first. That is how validation layers and reactive frameworks (like Vue) work.',
      lessons: ['Proxy Traps', 'Reflect', 'Validation Proxies', 'Observable Objects & Reactivity', REVIEW],
      explain: ['Why pair Proxy traps with Reflect?', 'How does a reactive framework know a value changed?'], build: ['A validation proxy', 'An observable object', 'A tiny reactive system'] },
    { n: 33, slug: 'RegularExpressions', title: 'Regular Expressions',
      bigIdea: 'A regex is a tiny pattern language for describing text. It is extremely powerful for small, regular patterns, and a trap for nested or complex grammars.',
      lessons: ['Matching & Character Classes', 'Groups & Named Groups', 'Lookahead & Lookbehind', 'Replacements', 'Parsing with Regex (and When Not To)', REVIEW],
      explain: ['Greedy vs lazy quantifiers?', 'Why can\'t regex reliably parse HTML?', 'What is catastrophic backtracking?'] },
    { n: 34, slug: 'TypedArraysAndBinaryData', title: 'Typed Arrays & Binary Data',
      bigIdea: 'Under every string, image and network packet are raw bytes. ArrayBuffer is a box of bytes; typed arrays and DataView are the glasses you look through to read them as numbers.',
      lessons: ['ArrayBuffer', 'Typed Arrays', 'DataView & Endianness', 'Encoding: TextEncoder & TextDecoder', 'Node.js Buffers', REVIEW],
      explain: ['Why do typed arrays exist when we have normal arrays?', 'What is endianness?'], build: ['Parse a binary file header (e.g. PNG / BMP)'] },
  ] },
  { n: 15, part: 1, slug: 'MemoryAndPerformance', title: 'Memory & Performance', weeks: 2, goal: 'Know where memory goes and where time goes, and prove it with measurements.', modules: [
    { n: 35, slug: 'MemoryManagement', title: 'Memory Management',
      bigIdea: 'The garbage collector is a cleaner who throws away anything nobody can reach any more. Memory leaks are things you accidentally keep reachable.',
      lessons: ['Stack & Heap', 'References & Reachability', 'Garbage Collection', 'Memory Leaks (and Finding Them)', 'WeakRef & FinalizationRegistry', REVIEW],
      explain: ['What makes an object eligible for garbage collection?', 'Name four common leak sources in JS apps.', 'How do you find a leak with DevTools?'] },
    { n: 36, slug: 'JavaScriptPerformance', title: 'JavaScript Performance',
      bigIdea: 'Performance work is detective work: measure, find the one hot spot, fix it, measure again. Guessing wastes time.',
      lessons: ['Measure First: Profiling', 'Complexity in Practice', 'DOM Performance: Layout Thrashing & Batching', 'Allocation & Hot Paths', 'Memoization & Caching Trade-offs', REVIEW],
      explain: ['What is layout thrashing?', 'Why can memoization make things slower?', 'How do you read a flame graph?'] },
  ] },
  { n: 16, part: 1, slug: 'DataStructuresAndAlgorithms', title: 'Data Structures & Algorithms in JavaScript', weeks: 6, goal: 'Implement the classic structures and algorithms yourself, and choose between them using complexity.', modules: [
    { n: 37, slug: 'AlgorithmicThinking', title: 'Algorithmic Thinking', bigIdea: 'An algorithm is a recipe precise enough for a robot. The skill is turning a fuzzy requirement into exact steps.', lessons: ['From Requirements to Algorithms', 'A Problem-Solving Framework', 'Worked Problems', REVIEW], explain: ['Describe your step-by-step approach to an unseen problem.'] },
    { n: 38, slug: 'Complexity', title: 'Complexity', bigIdea: 'Big-O asks: if the input gets 10× bigger, how much more work is there? It counts steps, not seconds.', lessons: ['Big-O Intuition', 'O(1), O(log n), O(n)', 'O(n log n) and O(n²)', 'Space Complexity', REVIEW], explain: ['Give a JS example for each common complexity class.', 'Why is O(n log n) the best general comparison sort?'] },
    { n: 39, slug: 'Stack', title: 'Stack', bigIdea: 'Last in, first out, like a stack of plates.', lessons: DS('Stack'), explain: ['Where does JS itself use a stack?'] },
    { n: 40, slug: 'Queue', title: 'Queue', bigIdea: 'First in, first out, like a line at a shop.', lessons: DS('Queue'), explain: ['Why is array.shift() a slow queue?'] },
    { n: 41, slug: 'LinkedList', title: 'Linked List', bigIdea: 'A treasure hunt: each item holds the clue to the next.', lessons: DS('Linked List'), explain: ['Linked list vs array: which operations win and lose?'] },
    { n: 42, slug: 'HashTable', title: 'Hash Table', bigIdea: 'A magic filing system that computes which drawer to use from the key itself.', lessons: DS('Hash Table'), explain: ['What is a collision and how is it handled?'] },
    { n: 43, slug: 'Tree', title: 'Tree', bigIdea: 'A family tree: one root, children, grandchildren. The DOM is one.', lessons: DS('Tree'), explain: ['Why is a balanced BST O(log n)?'] },
    { n: 44, slug: 'Heap', title: 'Heap', bigIdea: 'A tournament bracket that always knows the current champion (the min or max).', lessons: DS('Heap'), explain: ['How does a heap implement a priority queue?'] },
    { n: 45, slug: 'Graph', title: 'Graph', bigIdea: 'A map of cities and roads: anything connected to anything.', lessons: DS('Graph'), explain: ['Adjacency list vs matrix?'] },
    { n: 46, slug: 'LinearSearch', title: 'Linear Search', bigIdea: 'Check every locker until you find it.', lessons: ALGO('Linear Search'), explain: ['When is linear search the right choice?'] },
    { n: 47, slug: 'BinarySearch', title: 'Binary Search', bigIdea: 'The guess-the-number game: halve the possibilities every time.', lessons: ALGO('Binary Search'), explain: ['Why must the data be sorted?', 'Where do binary-search off-by-one bugs come from?'] },
    { n: 48, slug: 'Sorting', title: 'Sorting', bigIdea: 'Many ways to line up the class by height, some much faster than others.', lessons: ['Bubble, Insertion & Selection Sort', 'Merge Sort', 'Quick Sort', 'Stability & JavaScript\'s sort()', 'Practice Problems', REVIEW], explain: ['Merge vs quick sort trade-offs?', 'What is a stable sort and why does it matter?'] },
    { n: 49, slug: 'Recursion', title: 'Recursion', bigIdea: 'Russian dolls: solve a problem by solving a smaller copy of the same problem.', lessons: ALGO('Recursion'), explain: ['Every recursive function needs which two parts?'] },
    { n: 50, slug: 'TreeTraversal', title: 'Tree Traversal', bigIdea: 'Visiting every family member in a planned order.', lessons: ['Depth-First: Pre, In & Post-Order', 'Breadth-First (Level Order)', 'Recursive vs Iterative Traversal', 'Practice Problems', REVIEW], explain: ['When do you want BFS instead of DFS?'] },
    { n: 51, slug: 'GraphTraversal', title: 'Graph Traversal', bigIdea: 'Exploring a maze without getting lost: remember where you have been.', lessons: ['BFS on Graphs', 'DFS on Graphs', 'Shortest Paths (unweighted, then Dijkstra)', 'Cycle Detection & Topological Sort', 'Practice Problems', REVIEW], explain: ['Why does BFS find the shortest path in an unweighted graph?'] },
    { n: 52, slug: 'DynamicProgrammingIntro', title: 'Dynamic Programming (Introduction)', bigIdea: 'Never solve the same small puzzle twice: write the answer down and reuse it.', lessons: ['Overlapping Subproblems', 'Memoization (Top-Down)', 'Tabulation (Bottom-Up)', 'Classic Problems', REVIEW], explain: ['How do you recognise a DP problem?'] },
  ] },
  { n: 17, part: 1, slug: 'DesignPatterns', title: 'JavaScript Design Patterns', weeks: 2, goal: 'Every pattern answers "what problem does this solve?", never "memorise this pattern".', modules: [
    { n: 53, slug: 'Factory', title: 'Factory', bigIdea: 'A factory hides "how to build it" behind "what I want".', lessons: PATTERN('Factory'), explain: ['What problem does a factory solve that `new` does not?'] },
    { n: 54, slug: 'Strategy', title: 'Strategy', bigIdea: 'Swap the algorithm like swapping a drill bit, without changing the drill.', lessons: PATTERN('Strategy'), explain: ['How does strategy remove if/else chains?'] },
    { n: 55, slug: 'Observer', title: 'Observer', bigIdea: 'A newsletter: subscribers get told when something happens.', lessons: PATTERN('Observer'), explain: ['How does observer reduce coupling, and what can go wrong (leaks)?'] },
    { n: 56, slug: 'Command', title: 'Command', bigIdea: 'Turn an action into an object you can queue, log or undo.', lessons: PATTERN('Command'), explain: ['How does command enable undo/redo?'] },
    { n: 57, slug: 'Adapter', title: 'Adapter', bigIdea: 'A travel plug adapter for code: make one interface fit another.', lessons: PATTERN('Adapter'), explain: ['Where would you put an adapter around a third-party API?'] },
    { n: 58, slug: 'ModulePattern', title: 'Module Pattern', bigIdea: 'Expose a small public surface, hide the rest.', lessons: PATTERN('Module'), explain: ['How do ES modules change the classic module pattern?'] },
    { n: 59, slug: 'DependencyInjection', title: 'Dependency Injection', bigIdea: 'Hand a function its tools instead of letting it go shopping for them.', lessons: PATTERN('Dependency Injection'), explain: ['Why does DI make testing easier?'] },
    { n: 60, slug: 'Repository', title: 'Repository', bigIdea: 'One librarian who knows where data lives, so the rest of the app never needs to.', lessons: PATTERN('Repository'), explain: ['What leaks if business logic talks to the database directly?'] },
  ] },
  { n: 18, part: 1, slug: 'TestingJavaScript', title: 'Testing JavaScript', weeks: 1, goal: 'Tests as a design tool and a safety net.', modules: [
    { n: 61, slug: 'TestingFundamentals', title: 'Testing Fundamentals', bigIdea: 'Tests are safety nets under a trapeze: with them you can attempt bold moves (refactors) without fear.',
      lessons: ['What & Why to Test', 'Unit vs Integration Tests', 'node:test & Assertions', 'Test Doubles: Stubs, Spies, Mocks, Fakes', REVIEW],
      explain: ['Stub vs spy vs mock vs fake?', 'What makes a test brittle?'] },
    { n: 62, slug: 'TestDrivenDevelopment', title: 'Test-Driven Development', bigIdea: 'Write the exam before the answer: red, green, refactor.',
      lessons: ['Red → Green → Refactor', 'TDD Kata', 'Testing Async Code', REVIEW], explain: ['Why write the failing test first?'] },
  ] },
  { n: 19, part: 1, slug: 'NodeJS', title: 'Node.js JavaScript', weeks: 3, goal: 'Understand server-side JavaScript runtime behaviour, before TypeScript.', modules: [
    { n: 63, slug: 'NodeRuntime', title: 'The Node.js Runtime', bigIdea: 'Node = V8 + libuv + APIs: JavaScript given the keys to the computer.', lessons: ['V8, libuv & Core APIs', 'process, env & argv', 'Node\'s Module System in Practice', REVIEW], explain: ['What does libuv do?'] },
    { n: 64, slug: 'FileSystem', title: 'File System', bigIdea: 'Reading and writing files: sync, callback and promise styles.', lessons: ['fs Sync vs Async vs Promises', 'Paths & Directories', 'Watching Files', REVIEW], explain: ['Why avoid sync fs calls in a server?'] },
    { n: 65, slug: 'BuffersAndStreams', title: 'Buffers & Streams', bigIdea: 'Streams are a hose instead of a bucket: process data as it flows, not all at once.', lessons: ['Buffers', 'Readable & Writable Streams', 'Transform Streams & pipeline()', 'Backpressure', REVIEW], explain: ['What is backpressure?'] },
    { n: 66, slug: 'EventsAndEventEmitter', title: 'Events & EventEmitter', bigIdea: 'The observer pattern built into Node.', lessons: ['EventEmitter', 'Error Events & once()', 'Building Evented APIs', REVIEW], explain: ['What happens if nobody listens to an "error" event?'] },
    { n: 67, slug: 'Processes', title: 'Processes', bigIdea: 'Running other programs, and using more than one CPU core.', lessons: ['Child Processes', 'Worker Threads', 'Signals & Graceful Shutdown', REVIEW], explain: ['Worker thread vs child process?'] },
    { n: 68, slug: 'HTTPAndCLIApplications', title: 'HTTP & CLI Applications', bigIdea: 'A web server is just a program that listens and replies; a CLI is a program that reads argv.', lessons: ['node:http from Scratch', 'Routing & Body Parsing by Hand', 'Building Real CLIs (parseArgs, readline)', REVIEW], explain: ['What does a framework like Express add on top of node:http?'] },
  ] },

  // ───────────────────────── PART II: TYPESCRIPT ─────────────────────────
  { n: 20, part: 2, slug: 'TypeScriptFoundations', title: 'TypeScript Foundations', weeks: 1, goal: 'What TypeScript is, and what it is not.', modules: [
    { n: 69, slug: 'WhyTypeScriptExists', title: 'Why TypeScript Exists', bigIdea: 'TypeScript is spell-check for your program\'s shapes. It runs before your code, then disappears: the JavaScript that runs is unchanged.',
      lessons: ['JavaScript + Static Types + Tooling', 'Compile Time vs Runtime', 'Static vs Dynamic Typing', 'Structural Typing', 'Type Inference', REVIEW],
      explain: ['What does "TypeScript disappears at runtime" mean for validation?', 'Structural vs nominal typing, with an example.'] },
    { n: 70, slug: 'BasicTypes', title: 'Basic Types', bigIdea: 'Labels for the kinds of values you already know from JavaScript.',
      lessons: ['Primitives', 'Arrays & Tuples', 'Object Types', 'null & undefined under strictNullChecks', 'Literal Types', REVIEW], explain: ['Tuple vs array?', 'Why are literal types so useful?'] },
    { n: 71, slug: 'SpecialTypes', title: 'Special Types: any, unknown, never, void', bigIdea: 'any turns the checker off; unknown says "check before you use it"; never means "can\'t happen"; void means "no useful return".',
      lessons: ['any', 'unknown (and any vs unknown)', 'never', 'void', REVIEW], explain: ['Why prefer unknown over any?', 'Where does never appear naturally?'] },
  ] },
  { n: 21, part: 2, slug: 'FunctionsAndObjects', title: 'Functions & Objects', weeks: 1, goal: 'Type the two building blocks of every program.', modules: [
    { n: 72, slug: 'FunctionTyping', title: 'Function Typing', bigIdea: 'A function type is a contract: these inputs in, that output out.',
      lessons: ['Parameter & Return Types', 'Optional, Default & Rest Parameters', 'Function Types & Call Signatures', 'Overloads', REVIEW], explain: ['When are overloads better than a union parameter?'] },
    { n: 73, slug: 'ObjectTypes', title: 'Object Types', bigIdea: 'Describe the shape of objects: which keys, which types, what can change.',
      lessons: ['Type Aliases vs Interfaces', 'Optional & Readonly Properties', 'Index Signatures', 'Excess Property Checks', REVIEW], explain: ['type vs interface: when do you pick each?'] },
  ] },
  { n: 22, part: 2, slug: 'TypeSystemMastery', title: 'Type System Mastery', weeks: 2, goal: 'Model "either/or" and "both" correctly, and let the compiler follow your logic.', modules: [
    { n: 74, slug: 'UnionAndIntersectionTypes', title: 'Union & Intersection Types', bigIdea: 'A | B means "one of these"; A & B means "all of these at once".',
      lessons: ['Union Types', 'Intersection Types', 'Choosing the One That Matches the Domain', REVIEW], explain: ['Why is (A | B) often confused with (A & B)?'] },
    { n: 75, slug: 'Narrowing', title: 'Narrowing', bigIdea: 'The compiler follows your if-statements and learns more about a value on each branch.',
      lessons: ['typeof, instanceof & in', 'Equality & Truthiness Narrowing', 'Control-Flow Analysis', 'User-Defined Type Guards', 'Assertion Functions', REVIEW], explain: ['Type predicate vs assertion function?'] },
    { n: 76, slug: 'DiscriminatedUnions', title: 'Discriminated Unions', bigIdea: 'Give every variant a name tag (status: "success" | "error") and the compiler checks you handled each one.',
      lessons: ['The Tag Property', 'Exhaustiveness Checking with never', 'Modelling UI & Async State', REVIEW], explain: ['How does a discriminated union make invalid states unrepresentable?'] },
  ] },
  { n: 23, part: 2, slug: 'Generics', title: 'Generics', weeks: 2, goal: 'Write code that works for many types without losing type information.', modules: [
    { n: 77, slug: 'GenericsFundamentals', title: 'Generics Fundamentals', bigIdea: 'A generic is a type-shaped blank to be filled in later, like a form with "____".',
      lessons: ['Why Generics Exist', 'Generic Functions', 'Generic Types & Interfaces', 'Inference of Type Arguments', REVIEW], explain: ['What does <T> buy you over any?'] },
    { n: 78, slug: 'GenericConstraints', title: 'Generic Constraints', bigIdea: 'T extends X: "fill in any type, as long as it has what I need".',
      lessons: ['extends Constraints', 'Constraints with keyof', 'Default Type Parameters', REVIEW], explain: ['When is a constraint too strict?'] },
    { n: 79, slug: 'GenericAPIs', title: 'Generic APIs', bigIdea: 'Design reusable, strongly typed building blocks.',
      lessons: ['Generic Collections', 'Result Types', 'Generic Repositories', 'Typed API Clients', 'Typed Event Systems', REVIEW], explain: ['How do you keep generic APIs readable?'] },
  ] },
  { n: 24, part: 2, slug: 'AdvancedTypeScript', title: 'Advanced TypeScript', weeks: 4, goal: 'Type-level operators: compute new types from existing ones.', modules: [
    { n: 80, slug: 'Keyof', title: 'keyof', bigIdea: 'keyof T: the list of a type\'s key names, as a type.', lessons: ['keyof Basics', 'keyof with Generics', REVIEW], explain: ['What does keyof give for an index signature?'] },
    { n: 81, slug: 'TypeofTypeOperator', title: 'typeof (type operator)', bigIdea: 'Borrow the type of an existing value.', lessons: ['typeof in Type Positions', 'as const + typeof', REVIEW], explain: ['Value-space vs type-space?'] },
    { n: 82, slug: 'IndexedAccessTypes', title: 'Indexed Access Types', bigIdea: 'T["key"]: look up the type of one property.', lessons: ['T[K]', 'Array Element Types: T[number]', REVIEW], explain: ['How do you get the element type of an array type?'] },
    { n: 83, slug: 'MappedTypes', title: 'Mapped Types', bigIdea: 'A loop over keys, at the type level.', lessons: ['Basic Mapped Types', 'Modifiers (readonly, ?)', 'Key Remapping with as', REVIEW], explain: ['How is Partial<T> implemented?'] },
    { n: 84, slug: 'ConditionalTypes', title: 'Conditional Types', bigIdea: 'An if/else for types: T extends U ? X : Y.', lessons: ['Conditional Type Basics', 'Distributive Conditional Types', REVIEW], explain: ['Why does a conditional type distribute over unions?'] },
    { n: 85, slug: 'Infer', title: 'infer', bigIdea: 'Pattern-match a type and pull a piece out of it.', lessons: ['infer Basics', 'Extracting Return, Parameter & Promise Types', REVIEW], explain: ['How is ReturnType<T> built with infer?'] },
    { n: 86, slug: 'TemplateLiteralTypes', title: 'Template Literal Types', bigIdea: 'String patterns as types, e.g. `user:${string}`.', lessons: ['Template Literal Type Basics', 'Intrinsic String Types (Uppercase, …)', 'Typed Event Names & Routes', REVIEW], explain: ['Where do template literal types prevent real bugs?'] },
    { n: 87, slug: 'UtilityTypes', title: 'Utility Types', bigIdea: 'The standard library of type transformations. Rebuild each one yourself.', lessons: ['Partial, Required, Readonly', 'Pick, Omit, Record', 'Exclude, Extract, NonNullable', 'ReturnType, Parameters, Awaited', 'Recreate Them Yourself', REVIEW], explain: ['Implement Pick and Omit from scratch.'] },
  ] },
  { n: 25, part: 2, slug: 'ClassesAndOOP', title: 'Classes & OOP in TypeScript', weeks: 1, goal: 'Typed object-oriented design.', modules: [
    { n: 88, slug: 'ClassesInTypeScript', title: 'Classes in TypeScript', bigIdea: 'Classes with contracts: access modifiers, abstract classes, interfaces and generics.',
      lessons: ['Access Modifiers (and #private)', 'Abstract Classes', 'implements & Interfaces', 'Generic Classes', 'Inheritance vs Composition, Typed', REVIEW], explain: ['private vs #private?', 'Abstract class vs interface?'] },
  ] },
  { n: 26, part: 2, slug: 'ModulesAndConfiguration', title: 'Modules & Configuration', weeks: 2, goal: 'Configure TypeScript professionally and understand module resolution instead of copy-pasting configs.', modules: [
    { n: 89, slug: 'Tsconfig', title: 'tsconfig', bigIdea: 'tsconfig.json is the compiler\'s instruction sheet. Each option answers a question about your runtime.',
      lessons: ['strict and Its Family', 'target, lib & module', 'moduleResolution', 'paths, declaration & sourceMap', 'Build Configurations', REVIEW], explain: ['What does each strict sub-flag catch?'] },
    { n: 90, slug: 'ModuleResolution', title: 'Module Resolution', bigIdea: 'How "import x from \'y\'" turns into a real file, in Node, bundlers and TypeScript.',
      lessons: ['ESM vs CommonJS in TypeScript', 'package.json type, exports & imports', 'Node16/NodeNext vs Bundler Resolution', 'Debugging Resolution Errors', REVIEW], explain: ['Why do ESM imports in TS need .js extensions under NodeNext?'] },
  ] },
  { n: 27, part: 2, slug: 'DeclarationFiles', title: 'Declaration Files', weeks: 2, goal: 'Describe JavaScript to TypeScript, and publish typed libraries.', modules: [
    { n: 91, slug: 'DTSFiles', title: '.d.ts Files', bigIdea: 'A .d.ts file is a map of a JavaScript library\'s shape, with no code inside.',
      lessons: ['What .d.ts Files Are', 'Writing Declarations for JS Code', 'DefinitelyTyped & @types', 'Module Augmentation', REVIEW], explain: ['declare module vs global augmentation?'] },
    { n: 92, slug: 'LibraryAuthoring', title: 'Library Authoring', bigIdea: 'Design a public API, ship types with it, and version it responsibly.',
      lessons: ['Designing a Public API', 'Generating Declarations', 'Package exports', 'Semantic Versioning & Breaking Changes', REVIEW], explain: ['What counts as a breaking change in a type?'] },
  ] },
  { n: 28, part: 2, slug: 'TypeLevelProgramming', title: 'Type-Level Programming', weeks: 3, goal: 'Complex, reusable type relationships, while keeping readability first.', modules: [
    { n: 93, slug: 'AdvancedGenericProgramming', title: 'Advanced Generic Programming', bigIdea: 'Generics that relate many types to each other.', lessons: ['Higher-Order Generic Functions', 'Inference Tricks & const Type Parameters', 'Builder APIs', REVIEW], explain: ['How do you keep inference working through several calls?'] },
    { n: 94, slug: 'RecursiveTypes', title: 'Recursive Types', bigIdea: 'Types that refer to themselves: JSON, trees, deep paths.', lessons: ['Recursive Type Aliases', 'DeepPartial & DeepReadonly', 'Recursion Limits', REVIEW], explain: ['Why does TypeScript limit recursion depth?'] },
    { n: 95, slug: 'TypeTransformations', title: 'Type Transformations', bigIdea: 'Reshape types systematically: flatten, rename, filter keys.', lessons: ['Key Filtering', 'Flattening & Merging', 'Path Types', REVIEW], explain: ['When is a transformation too clever?'] },
    { n: 96, slug: 'TypeChallenges', title: 'Type Challenges', bigIdea: 'Puzzles that sharpen type-level skill. Readability still wins in real code.', lessons: ['Easy Challenges', 'Medium Challenges', 'Hard Challenges', 'Readability Review', REVIEW], explain: ['Explain one hard solution in plain words.'] },
  ] },
  { n: 29, part: 2, slug: 'TypeScriptArchitecture', title: 'TypeScript Architecture', weeks: 3, goal: 'Use types to make invalid states hard to represent, and validate what types cannot see.', modules: [
    { n: 97, slug: 'DomainModeling', title: 'Domain Modeling', bigIdea: 'Model User, Order, Payment, Course, Enrollment, Permission and Invoice so that wrong combinations cannot even be written.',
      lessons: ['Entities & Value Objects', 'Branded Types', 'Making Invalid States Unrepresentable', 'State Machines in Types', REVIEW], explain: ['What is a branded type and why use one for IDs?'] },
    { n: 98, slug: 'ErrorModeling', title: 'Error Modeling', bigIdea: 'Put failures in the function\'s signature: Result<T, E>.', lessons: ['Throwing vs Returning Errors', 'Result<T, E>', 'Discriminated Error Systems', REVIEW], explain: ['When is throwing still the right choice?'] },
    { n: 99, slug: 'TypeSafeAPIs', title: 'Type-Safe APIs', bigIdea: 'One contract shared by client and server, so they cannot drift apart.', lessons: ['Shared Contracts', 'End-to-End Typing', 'Versioning Contracts', REVIEW], explain: ['Where can end-to-end types still lie to you?'] },
    { n: 100, slug: 'RuntimeValidation', title: 'Runtime Validation vs Static Types', bigIdea: 'TypeScript vanishes at runtime, so data from outside (HTTP, files, users) must be checked by real code at the boundary.',
      lessons: ['Why Types Disappear', 'Parse, Don\'t Validate', 'Schema Validation & Inferred Types', 'Validating at the Boundaries', REVIEW], explain: ['Why is `as User` on API data dangerous?'] },
  ] },
  { n: 30, part: 2, slug: 'LargeTypeScriptSystems', title: 'Large TypeScript Systems', weeks: 3, goal: 'Structure, share and migrate large codebases.', modules: [
    { n: 101, slug: 'ProjectStructure', title: 'Project Structure', bigIdea: 'Folders are architecture: they decide what can depend on what.', lessons: ['Layering & Boundaries', 'Feature vs Layer Folders', 'Enforcing Boundaries', REVIEW], explain: ['How do you stop the UI importing the database layer?'] },
    { n: 102, slug: 'Monorepos', title: 'Monorepos', bigIdea: 'Many packages, one repository, shared types.', lessons: ['Workspaces', 'Shared Types Packages', 'Project References', REVIEW], explain: ['What do project references speed up?'] },
    { n: 103, slug: 'RefactoringLargeCodebases', title: 'Refactoring Large Codebases', bigIdea: 'Migrate gradually: JSDoc → @ts-check → .ts → strict, without stopping the world.', lessons: ['Incremental Adoption Paths', 'JSDoc & @ts-check', 'Tightening strict Flag by Flag', 'Safe Refactoring Techniques', REVIEW], explain: ['Plan a 6-step migration of a 50k-line JS app.'] },
  ] },
];

// Projects are done AFTER the phase named in `after`.
export const projects = [
  { id: 'JP1', part: 1, slug: 'CLITaskManager', title: 'CLI Task Manager', after: 9, weeks: 1, brief: 'A pure-JavaScript command-line task manager that persists tasks to a JSON file.', features: ['add / list / done / remove / edit commands', 'Priorities, due dates and filtering', 'Custom error classes with friendly messages', 'Undo last action', 'Unit tests for all core logic'] },
  { id: 'JP2', part: 1, slug: 'PersonalFinanceSystem', title: 'Personal Finance System', after: 10, weeks: 1, brief: 'A browser app for income and expenses built with the raw DOM and local persistence.', features: ['Income / expense entries with categories', 'Filtering and totals', 'Money stored as integer cents', 'localStorage persistence with versioned data', 'Event delegation for all list interactions'] },
  { id: 'JP3', part: 1, slug: 'KanbanBoard', title: 'Kanban Board', after: 11, weeks: 1, brief: 'Trello-style boards with drag and drop, filtering and a central state store.', features: ['Boards, columns, cards', 'Drag & drop', 'Filtering & search', 'Single source of truth + re-render', 'Simulated async save with loading and error states'] },
  { id: 'JP4', part: 1, slug: 'APIDashboard', title: 'API Dashboard', after: 12, weeks: 1, brief: 'A dashboard combining several public APIs, built to survive a bad network.', features: ['At least 4 APIs', 'Retries with backoff', 'Caching with expiry', 'Cancellation of stale requests', 'Loading / empty / error states'] },
  { id: 'JP5', part: 1, slug: 'MiniUtilityLibrary', title: 'Mini JavaScript Utility Library', after: 13, weeks: 1, brief: 'Your own lodash-style library, as an ES module package with tests and docs.', features: ['deepClone, debounce, throttle, memoize', 'groupBy, compose, curry, retry', '100% of functions tested', 'README with API docs', 'Published structure (package.json exports)'] },
  { id: 'JP6', part: 1, slug: 'TinyReactiveFramework', title: 'Tiny Reactive Framework', after: 14, weeks: 2, brief: 'A small framework with state, reactivity, DOM updates, components and events, to learn why React and Vue exist.', features: ['Reactive state (Proxy-based)', 'Automatic DOM updates', 'Components with props', 'Event binding', 'A demo app built with it'] },
  { id: 'JP7', part: 1, slug: 'NodeHTTPFramework', title: 'Node.js HTTP Framework', after: 19, weeks: 1, brief: 'A tiny Express-like framework: enough to understand its architecture, not a clone.', features: ['app.get / app.post / app.use', 'Middleware chain with next()', 'Route params & JSON bodies', 'Central error-handling middleware', 'A sample API built on it'] },
  { id: 'JSC', part: 1, slug: 'JavaScriptCapstone', title: 'JavaScript Final Capstone: A Complete App Without Frameworks', after: 19, weeks: 3, brief: 'A full application proving you understand JavaScript itself, not just React.', features: ['Frontend (vanilla JS)', 'Node backend on your own JP7 framework or node:http', 'REST API', 'Authentication concepts (sessions, hashing)', 'Database interface (repository layer)', 'Async operations, validation, error handling, logging', 'Tests (unit + integration)', 'Modular architecture document'] },
  { id: 'TP1', part: 2, slug: 'ConvertJavaScriptProject', title: 'Convert an Existing JavaScript Project', after: 22, weeks: 1, brief: 'Migrate your Personal Finance System (JP2) to TypeScript.', features: ['strict: true', 'No `any` unless justified in a comment', 'Discriminated unions for UI state', 'Migration log: bugs the types caught'] },
  { id: 'TP2', part: 2, slug: 'TypeSafeRESTClient', title: 'Type-Safe REST Client', after: 23, weeks: 1, brief: 'A small REST client with generic, typed methods.', features: ['client.get<User>(…)', 'client.post<CreateUser, User>(…)', 'Typed errors (Result type)', 'Timeouts, retries, cancellation'] },
  { id: 'TP3', part: 2, slug: 'ValidationLibrary', title: 'Validation Library', after: 24, weeks: 1, brief: 'A mini schema-validation library (Zod-style) whose schemas infer static types.', features: ['string / number / boolean / object / array / union schemas', 'Infer<typeof schema>', 'Readable error paths', 'Tests for every schema kind'] },
  { id: 'TP4', part: 2, slug: 'GenericRepositorySystem', title: 'Generic Repository System', after: 24, weeks: 1, brief: 'Repository<T, ID> with strongly typed CRUD and in-memory + file implementations.', features: ['Repository<T, ID> interface', 'Typed queries / filters', 'Two implementations behind one interface', 'Contract tests shared by both'] },
  { id: 'TP5', part: 2, slug: 'TypeSafeEventSystem', title: 'Type-Safe Event System', after: 24, weeks: 1, brief: 'An event emitter where event names determine payload types.', features: ['emit("user:created", user) is type-checked', 'Wrong payloads fail at compile time', 'on / off / once', 'Tests with @ts-expect-error for invalid calls'] },
  { id: 'TP6', part: 2, slug: 'TypeSafeStateLibrary', title: 'Type-Safe State Management Library', after: 25, weeks: 1, brief: 'A small Zustand-like store with full inference.', features: ['create(set => ({ … }))', 'Typed selectors & subscriptions', 'Middleware (logging, persistence)', 'Demo app'] },
  { id: 'TP7', part: 2, slug: 'PublishTypeScriptPackage', title: 'Publish Your Own TypeScript Package', after: 27, weeks: 1, brief: 'Ship one of your libraries as a real npm package.', features: ['Documentation', 'Tests + CI', 'Declaration files', 'ESM + package exports', 'Semantic versioning & changelog'] },
];

export const finals = [
  { id: 'FINAL', slug: 'FinalCapstone', title: 'Final JavaScript + TypeScript Capstone: A Production-Grade Platform', weeks: 5,
    brief: 'TypeScript frontend → typed API layer → Node/TypeScript backend → domain layer → data layer → database. No React required at first.',
    features: ['Strict TypeScript everywhere', 'Authentication & authorization', 'A complex domain model', 'API with shared contracts', 'Database', 'Async processing (jobs/queues)', 'Runtime validation at every boundary', 'Caching', 'Error architecture (Result types + layers)', 'Logging', 'Unit, integration and E2E tests', 'CI pipeline', 'Architecture documentation'] },
  { id: 'RESCUE', slug: 'FinalChallenge-RescueTheCodebase', title: 'Final Advanced Challenge: Rescue the Codebase', weeks: 1,
    brief: 'You receive an intentionally bad JavaScript codebase. Your assignment: turn it into professional software, and defend every major decision.',
    features: ['1. Find bugs', '2. Identify architectural problems', '3. Add TypeScript', '4. Improve the domain model', '5. Refactor the modules', '6. Improve error handling', '7. Add tests', '8. Improve performance', '9. Document the architecture', '10. Defend every decision (recorded presentation)'] },
];
